#!/usr/bin/env bash

## Initialise the project
##
## Usage: fin init

fin start

# Generate a salt value.
fin exec 'openssl rand -base64 32 > ~/salt.txt'

fin composer install --optimize-autoloader --prefer-source

fin drush site-install -y --account-pass=admin

fin uli
