#!/usr/bin/env bash

## Initialise the project
##
## Usage: fin init

fin start

git clone --branch 7.x https://git.drupal.org/project/drupal.git drupal

cp -R static-files/* drupal

cd drupal

fin drush site-install -y --account-pass=admin
fin drush pm-disable -y overlay
fin drush pm-uninstall -y overlay
fin drush pm-enable -y simpletest

fin uli
