#!/usr/bin/env bash

## Initialise the project
##
## Usage: fin init

fin start

git clone --branch 8.7.x https://git.drupal.org/project/drupal.git --depth 1 core

cp -R static-files/* core

cd core

# Generate a salt value.
fin exec 'openssl rand -base64 32 > ~/salt.txt'

fin composer install --optimize-autoloader --prefer-source

fin drush site-install -y --account-pass=admin

fin uli
